### ISSUE TITLE
how run server? can u help pls

### ISSUE THREAD

**Issue by hdev72** [MrLetsplay2003/Secret-Reichstag-Server#15]

**Comment by MrLetsplay2003** [comment]
I've created a release with the server JAR file. You can download it from there and run it using Java 11 or higher:
https://github.com/MrLetsplay2003/Secret-Reichstag-Server/releases/

**Comment by hdev72** [comment]
thank you so much dear friend.
i think about another Feature: automatic match finding, user starting match finding and server creates rooms and starts when a room has 7 players, can you build that if u like , is that all server managing every thing like most popular games like dota2, good luck dear.
with respect

**Comment by MrLetsplay2003** [comment]
I've moved this suggestion into a new issue (#16) as I want to implement something similar at some point. Thanks for the suggestion
